# Generated by Django 5.0.3 on 2024-03-07 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=75, verbose_name='Course')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('time_of_post', models.DateTimeField(verbose_name='Time of Post')),
                ('post_description', models.CharField(max_length=500, null=True, verbose_name='Description')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='PDF File')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Video File')),
                ('video_website_address', models.URLField(blank=True, null=True, verbose_name='Video Adress')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number')),
                ('username', models.CharField(max_length=75, verbose_name='Username')),
                ('password', models.CharField(max_length=75, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='CoreSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75, verbose_name='Core Subject')),
                ('courses', models.ManyToManyField(blank=True, null=True, to='users.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='all_tickets',
            field=models.ManyToManyField(blank=True, null=True, to='users.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
        ),
    ]
