# Generated by Django 5.0.3 on 2024-03-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_ticket_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='video_file',
            field=models.URLField(blank=True, null=True, verbose_name='Video File'),
        ),
    ]
