# Generated by Django 5.0.3 on 2024-03-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_ticket_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Video File'),
        ),
    ]
