# Generated by Django 5.0.3 on 2024-04-04 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_ticket_video_website_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='video_website_address',
            field=models.URLField(blank=True, null=True, verbose_name='Video Adress'),
        ),
    ]
